language: node_js
node_js:
  - "10"

# safelist branches
branches:
  only:
    - master
    - staging

before_install:
  # execute all of the commands which need to be executed before installing dependencies
  - chmod +x test.sh

install:
  - npm install

before_script:
  # execute all of the commands which need to be executed before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - ./test.sh

deploy:
  provider: gae
    keyfile: "gae-creds.json"
    project: traviscicd
    no_promote: true
    version: staging
    on:
      branch: staging