language: node_js
node_js:
- "10"

before_install:
- openssl aes-256-cbc -K $encrypted_c423808ed406_key -iv $encrypted_c423808ed406_iv
  -in gae-creds.json.enc -out gae-creds.json -d
- chmod +x test.sh

install:
- npm install

script:
- "./test.sh"

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: gae-creds.json
  roject: traviscicd
  no_promote: true
  version: staging
  on:
    branch: staging