language: node_js
node_js:
- "10"
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_c423808ed406_key -iv $encrypted_c423808ed406_iv
  -in gae-creds.json.enc -out gae-creds.json -d
- chmod +x test.sh
install:
- npm install
before_script: 
script:
- "./test.sh"
