language: node_js
node_js:
- "10"

before_install:
- openssl aes-256-cbc -K $encrypted_c423808ed406_key -iv $encrypted_c423808ed406_iv
  -in gae-creds.json.enc -out gae-creds.json -d

install:
- npm install

script:
- npm run build
- npm test

deploy:
  - provider: gae
    skip_cleanup: true
    keyfile: gae-creds.json
    project: traviscicd
    no_promote: true
    version: qa-staging
    on:
      branch: staging
  - provider: gae
    skip_cleanup: true
    keyfile: gae-creds.json
    project: traviscicd
    version: production
    on:
      branch: master
